name: E2E Regression

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '00 8 * * *'
  workflow_dispatch:

env:
  TARGET: "%regex[.*Tests.*],com.automationexercices.tests.**.**.com.automationexercices.tests.**"

jobs:
  Chrome_Linux_Test:
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.8

      - name: Running Tests
        run: mvn test -Dtest="${TARGET}" -DexecutionType="LocalHeadless" -DbrowserType="chrome" clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Chrome_Linux_Report
          path: "test-output/reports/*.html"



  Edge_Windows_Test:
    runs-on: windows-latest
    permissions:
      checks: write
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.8

      - name: Running Tests
        run: mvn test -Dtest="${TARGET}" -DexecutionType="LocalHeadless" -DbrowserType="Edge" clean test

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Edge_Window_Report
          path: "test-output/reports/*.html"